/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clase_ventasordenadores;

import java.awt.List;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.HashSet;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.ListModel;

/**
 *
 * @author jojo
 */
public class VentaGUI extends javax.swing.JFrame {
    public static ArrayList<Venta> listaVentas = new ArrayList<>();
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentaGUI.class.getName());

    /**
     * Creates new form VentaGUI
     */
    public VentaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgProcesadores = new javax.swing.ButtonGroup();
        bgMemoria = new javax.swing.ButtonGroup();
        bgMonitor = new javax.swing.ButtonGroup();
        bgDiscoDuro = new javax.swing.ButtonGroup();
        jOptBus1 = new javax.swing.JOptionPane();
        jOptEli1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jnombreCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLocalidad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPro1 = new javax.swing.JRadioButton();
        jPro2 = new javax.swing.JRadioButton();
        jPro3 = new javax.swing.JRadioButton();
        jPro4 = new javax.swing.JRadioButton();
        jMem1 = new javax.swing.JRadioButton();
        jMem2 = new javax.swing.JRadioButton();
        jMem3 = new javax.swing.JRadioButton();
        jMem4 = new javax.swing.JRadioButton();
        jMon1 = new javax.swing.JRadioButton();
        jMon2 = new javax.swing.JRadioButton();
        jMon3 = new javax.swing.JRadioButton();
        jMon4 = new javax.swing.JRadioButton();
        jDis1 = new javax.swing.JRadioButton();
        jDis2 = new javax.swing.JRadioButton();
        jDis3 = new javax.swing.JRadioButton();
        jDis4 = new javax.swing.JRadioButton();
        jOpc1 = new javax.swing.JCheckBox();
        jOpc2 = new javax.swing.JCheckBox();
        jOpc4 = new javax.swing.JCheckBox();
        jOpc3 = new javax.swing.JCheckBox();
        jBAdd = new javax.swing.JButton();
        jBEli = new javax.swing.JButton();
        jBBus = new javax.swing.JButton();
        JBSalir = new javax.swing.JButton();
        jBCan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jBGVe = new javax.swing.JButton();
        jBMVe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(760, 440));
        setResizable(false);

        jPanel1.setEnabled(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 440));

        jLabel1.setText("Nombre del Cliente");
        jLabel1.setPreferredSize(new java.awt.Dimension(120, 20));

        jnombreCliente.setToolTipText("");
        jnombreCliente.setMinimumSize(new java.awt.Dimension(120, 40));
        jnombreCliente.setPreferredSize(new java.awt.Dimension(120, 30));
        jnombreCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jnombreClienteFocusGained(evt);
            }
        });
        jnombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnombreClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Localidad");
        jLabel2.setPreferredSize(new java.awt.Dimension(120, 20));

        jLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Villalba", "Alpedrete", "Galapagar", "Guadarrama", "Moralzarzal" }));
        jLocalidad.setEnabled(false);
        jLocalidad.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel3.setText("Lista de Clientes");

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel4.setText("Procesador");
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel5.setText("Memoria");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel6.setText("Monitor");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel7.setText("Disco Duro");
        jLabel7.setPreferredSize(new java.awt.Dimension(80, 20));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel8.setText("Opciones");
        jLabel8.setPreferredSize(new java.awt.Dimension(80, 20));

        bgProcesadores.add(jPro1);
        jPro1.setSelected(true);
        jPro1.setText("P4 3.0 Gb");
        jPro1.setEnabled(false);
        jPro1.setName("P4 3.0 Gb"); // NOI18N
        jPro1.setPreferredSize(new java.awt.Dimension(120, 20));

        bgProcesadores.add(jPro2);
        jPro2.setText("P4 3.2 Gb");
        jPro2.setEnabled(false);
        jPro2.setPreferredSize(new java.awt.Dimension(120, 20));

        bgProcesadores.add(jPro3);
        jPro3.setText("P4 Celeron");
        jPro3.setEnabled(false);
        jPro3.setPreferredSize(new java.awt.Dimension(120, 20));

        bgProcesadores.add(jPro4);
        jPro4.setText("AMD 650");
        jPro4.setEnabled(false);
        jPro4.setPreferredSize(new java.awt.Dimension(120, 20));

        bgMemoria.add(jMem1);
        jMem1.setSelected(true);
        jMem1.setText("128 Mb");
        jMem1.setEnabled(false);
        jMem1.setPreferredSize(new java.awt.Dimension(120, 20));

        bgMemoria.add(jMem2);
        jMem2.setText("256 Mb");
        jMem2.setEnabled(false);
        jMem2.setPreferredSize(new java.awt.Dimension(120, 20));

        bgMemoria.add(jMem3);
        jMem3.setText("512 Mb");
        jMem3.setEnabled(false);
        jMem3.setPreferredSize(new java.awt.Dimension(120, 20));

        bgMemoria.add(jMem4);
        jMem4.setText("1024 Mb");
        jMem4.setEnabled(false);
        jMem4.setPreferredSize(new java.awt.Dimension(120, 20));

        bgMonitor.add(jMon1);
        jMon1.setSelected(true);
        jMon1.setText("15\"");
        jMon1.setEnabled(false);
        jMon1.setPreferredSize(new java.awt.Dimension(120, 20));

        bgMonitor.add(jMon2);
        jMon2.setText("17\"");
        jMon2.setEnabled(false);
        jMon2.setPreferredSize(new java.awt.Dimension(120, 20));

        bgMonitor.add(jMon3);
        jMon3.setText("TFT 15\"");
        jMon3.setEnabled(false);
        jMon3.setPreferredSize(new java.awt.Dimension(120, 20));

        bgMonitor.add(jMon4);
        jMon4.setText("TFT 17\"");
        jMon4.setEnabled(false);
        jMon4.setPreferredSize(new java.awt.Dimension(120, 20));

        bgDiscoDuro.add(jDis1);
        jDis1.setSelected(true);
        jDis1.setText("60 Gb");
        jDis1.setEnabled(false);
        jDis1.setPreferredSize(new java.awt.Dimension(120, 20));

        bgDiscoDuro.add(jDis2);
        jDis2.setText("80 Gb");
        jDis2.setEnabled(false);
        jDis2.setPreferredSize(new java.awt.Dimension(120, 20));

        bgDiscoDuro.add(jDis3);
        jDis3.setText("120 Gb");
        jDis3.setEnabled(false);
        jDis3.setPreferredSize(new java.awt.Dimension(120, 20));

        bgDiscoDuro.add(jDis4);
        jDis4.setText("200 Gb");
        jDis4.setEnabled(false);
        jDis4.setPreferredSize(new java.awt.Dimension(120, 20));

        jOpc1.setSelected(true);
        jOpc1.setText("Grabadora DVD");
        jOpc1.setEnabled(false);
        jOpc1.setPreferredSize(new java.awt.Dimension(120, 20));

        jOpc2.setSelected(true);
        jOpc2.setText("Wifi");
        jOpc2.setEnabled(false);
        jOpc2.setPreferredSize(new java.awt.Dimension(120, 20));

        jOpc4.setText("Backup / Restore");
        jOpc4.setEnabled(false);
        jOpc4.setPreferredSize(new java.awt.Dimension(120, 20));

        jOpc3.setText("Sintonizador TV");
        jOpc3.setEnabled(false);

        jBAdd.setText("Añadir");
        jBAdd.setEnabled(false);
        jBAdd.setPreferredSize(new java.awt.Dimension(80, 30));
        jBAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddActionPerformed(evt);
            }
        });

        jBEli.setText("Eliminar");
        jBEli.setEnabled(false);
        jBEli.setPreferredSize(new java.awt.Dimension(80, 30));
        jBEli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliActionPerformed(evt);
            }
        });

        jBBus.setText("Buscar");
        jBBus.setEnabled(false);
        jBBus.setPreferredSize(new java.awt.Dimension(80, 30));
        jBBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBusActionPerformed(evt);
            }
        });

        JBSalir.setText("Salir");
        JBSalir.setPreferredSize(new java.awt.Dimension(80, 30));
        JBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSalirActionPerformed(evt);
            }
        });

        jBCan.setText("Cancelar");
        jBCan.setPreferredSize(new java.awt.Dimension(80, 30));
        jBCan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCanActionPerformed(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(280, 140));
        jScrollPane1.setViewportView(jList1);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jList1FocusLost(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jBGVe.setText("Guardar Ventas");
        jBGVe.setPreferredSize(new java.awt.Dimension(130, 30));
        jBGVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGVeActionPerformed(evt);
            }
        });

        jBMVe.setText("Mostrar Ventas");
        jBMVe.setPreferredSize(new java.awt.Dimension(130, 30));
        jBMVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMVeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDis4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDis3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDis2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jOpc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jOpc3)
                                    .addComponent(jOpc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jMem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jMem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBEli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBMVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBGVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(109, 109, 109))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPro4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jMem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jMon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jMon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOpc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDis2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOpc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDis3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDis4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jOpc3)
                                .addGap(18, 18, 18)
                                .addComponent(jOpc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBEli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBGVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jBCan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(177, 177, 177))
        );

        jPro1.setActionCommand("P4 3.0 Gb");
        jPro2.setActionCommand("P4 3.2 Gb");
        jPro3.setActionCommand("P4 Celeron");
        jPro4.setActionCommand("AMD 650");
        jMem1.setActionCommand("128Mb");
        jMem2.setActionCommand("256Mb");
        jMem3.setActionCommand("512Mb");
        jMem4.setActionCommand("1024Mb");
        jMon1.setActionCommand("15\"");
        jMon2.setActionCommand("17\"");
        jMon3.setActionCommand("TFT 15\"");
        jMon4.setActionCommand("TFT 17\"");
        jDis1.setActionCommand("60 Gb");
        jDis2.setActionCommand("80 Gb");
        jDis3.setActionCommand("120 Gb");
        jDis4.setActionCommand("200 Gb");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 171, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Al 
     * @param evt 
     */
    private void jnombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnombreClienteActionPerformed
        setDefault();
        if (nombreCorrecto()){
            booleanButtons(true);
            jBAdd.setEnabled(true);
            jBBus.setEnabled(true);
            jLocalidad.grabFocus();
            //jnombreCliente.setEnabled(false);
        } else {
            jnombreCliente.grabFocus();
        }
        

    }//GEN-LAST:event_jnombreClienteActionPerformed
    
    //Botón Eliminar -> Borra el usuario seleccionado del JList
    private void jBEliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliActionPerformed
        String[] options = {"Eliminar", "Cancelar"};
        jnombreCliente.setText(jList1.getSelectedValue());
        int res = jOptEli1.showOptionDialog(
                null,
                "Deseas eliminar al usuario: " + jnombreCliente.getText(),
                "Eliminar Venta",
                jOptBus1.DEFAULT_OPTION,
                jOptBus1.YES_NO_OPTION,
                null,
                options,
                options[0]
        );
        if (res==1){
            jList1.clearSelection();
        } else {
            DefaultListModel demo = obtenerList();
            demo.remove(jList1.getSelectedIndex());
            listaVentas.remove(jList1.getSelectedIndex());
            jList1.setModel(demo);
            jBEli.setEnabled(false);
            jnombreCliente.setText("");
        }
        
    }//GEN-LAST:event_jBEliActionPerformed
    
    
    //Botón Buscar -> Muestra las Ventas del usuario que se nombre en NombreCliente 
    private void jBBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBusActionPerformed

        int res = 0;
        jBAdd.setEnabled(false);
        jnombreCliente.setEnabled(true);
       
        String nombre = jnombreCliente.getText();
        ArrayList<Venta> ventaFiltro = busquedaLista(nombre);
        
        if (ventaFiltro.size() == 0){
            setDefault();
            jOptBus1.showMessageDialog(null, "No se ha encontrado el cliente", "ResultadoBúsqueda", jOptBus1.INFORMATION_MESSAGE);

        } else {
            int indice = 0;
            while (res != 1){
                escogerVenta(ventaFiltro.get(indice));
                if (indice == ventaFiltro.size()-1){
                    jOptBus1.showMessageDialog(
                            null,
                            "Último usuario con nombre: " + jnombreCliente.getText(),
                            "ResultadoBúsqueda",
                            jOptBus1.INFORMATION_MESSAGE);
                    break;
                } else {
                    Object[] options = {"Si", "No"};
                    res = jOptBus1.showOptionDialog(
                        null,
                        "Se han encontrado varias ventas. ¿Quiere ver la siguiente?",
                        "¿Quiere Buscar Otra Venta?",
                        jOptBus1.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[0]);
                    if (res == 0){
                        setDefault();
                        indice += 1;
                    }
                }
            }
        }
        
    }//GEN-LAST:event_jBBusActionPerformed
    
    //Botón Salir -> Sale del Programa
    private void JBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSalirActionPerformed
        if (!listaVentas.isEmpty()){
            Object[] options = {"Cancelar","Salir Igualmente"};
            int res = jOptBus1.showOptionDialog(
                null,
                "Hay ventas no guardadas",
                "Hay ventas no guardadas",
                jOptBus1.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
            if (res == 1){
                System.exit(0);
            }
        } else {
            System.exit(0);
        }
    }//GEN-LAST:event_JBSalirActionPerformed
    
    //Botón Cancelar -> Vuelve al estado por defecto conservando las ventas
    private void jBCanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCanActionPerformed
        jnombreCliente.setText("");
        jnombreCliente.grabFocus();
        booleanButtons(false);
        jBAdd.setEnabled(false);
        jBBus.setEnabled(false);
    }//GEN-LAST:event_jBCanActionPerformed

    //Agrega la venta creada a la lista ventas
    private void jBAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddActionPerformed
        booleanButtons(false);
        listaVentas.add(crearVentas());
        addVenta();
        jnombreCliente.setText("");
        jnombreCliente.grabFocus();
        jBAdd.setEnabled(false);
        jBBus.setEnabled(false);
        setDefault();
    }//GEN-LAST:event_jBAddActionPerformed

    //Habilita el botón eliminar 
    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        if (!(jList1.getSelectedIndex() == -1)){
            jBEli.setEnabled(true);
            escogerVenta(listaVentas.get(jList1.getSelectedIndex()));
        } else {
            jBEli.setEnabled(false);
        }
    }//GEN-LAST:event_jList1ValueChanged

    private void jList1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jList1FocusLost
        //jList1.clearSelection();

    }//GEN-LAST:event_jList1FocusLost

    //Deselecciona de la JList y devuelve los botones al estado normal
    private void jnombreClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jnombreClienteFocusGained
        setDefault();
        jList1.clearSelection();
    }//GEN-LAST:event_jnombreClienteFocusGained
    
    //Muestra las ventas del archivo ventas, si han sido cargadas se deben guardar previamente
    private void jBGVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGVeActionPerformed
        if (listaVentas.isEmpty()){
            jOptBus1.showMessageDialog(
                null,
                "No hay ventas en la lista",
                "No hay ventas en la lista",
                jOptBus1.INFORMATION_MESSAGE);
        } else {
        
            GestorVentas gv = new GestorVentas();

            gv.escribirVentas(listaVentas);


            DefaultListModel model = new DefaultListModel();
            jList1.setModel(model);
            listaVentas.clear();
        }
    }//GEN-LAST:event_jBGVeActionPerformed
    
    //Guarda los objetos del archivo en una lista, mostrándolas en el JList
    private void jBMVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMVeActionPerformed
        
        GestorVentas gv = new GestorVentas();
        
        if(gv.fileRead()){
            listaVentas = gv.leerVentas();

            DefaultListModel model = new DefaultListModel();
            for (Venta ven : listaVentas){
                model.addElement(ven.getNombreCliente());
            }
            jList1.setModel(model);
            gv.borrarDatos();
        }
        
        
         
    }//GEN-LAST:event_jBMVeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() ->new VentaGUI().setVisible(true));
        
       
    }
    
    //Metodos
    
    /**
     * Activa o desactiva los botones en funcion del valor de attr
     * @param attr 
     */
    public void booleanButtons(boolean attr){
        //jnombreCliente.setEnabled(!attr);
        jnombreCliente.setEnabled(!attr);
        //Localidad
        jLocalidad.setEnabled(attr);
        //Grupo Procesadores
        jPro1.setEnabled(attr);
        jPro2.setEnabled(attr);
        jPro3.setEnabled(attr);
        jPro4.setEnabled(attr);
        //Grupo Memoria
        jMem1.setEnabled(attr);
        jMem2.setEnabled(attr);
        jMem3.setEnabled(attr);
        jMem4.setEnabled(attr);
        //Grupo Monitor
        jMon1.setEnabled(attr);
        jMon2.setEnabled(attr);
        jMon3.setEnabled(attr);
        jMon4.setEnabled(attr);
        //Grupo Disco Duro
        jDis1.setEnabled(attr);
        jDis2.setEnabled(attr);
        jDis3.setEnabled(attr);
        jDis4.setEnabled(attr);
        //Grupo Opciones
        jOpc1.setEnabled(attr);
        jOpc2.setEnabled(attr);
        jOpc3.setEnabled(attr);
        jOpc4.setEnabled(attr);   
    }
    
    
    /**
     * Crea un objeto Venta las opciones seleccionadas
     * @return Objeto Venta creado
     */
    public Venta crearVentas(){
        String nom = jnombreCliente.getText();
        String loc = (String)jLocalidad.getSelectedItem();
        String pro = bgProcesadores.getSelection().getActionCommand();
        String mem = bgMemoria.getSelection().getActionCommand();
        String mon = bgMonitor.getSelection().getActionCommand();
        String dis = bgDiscoDuro.getSelection().getActionCommand();
        boolean op1 = jOpc1.isSelected();
        boolean op2 = jOpc2.isSelected();
        boolean op3 = jOpc3.isSelected();
        boolean op4 = jOpc4.isSelected();
        Venta ven = new Venta(nom, loc, pro, mem, mon, dis, op1, op2, op3, op4);
        return ven;
        
    }
    
    
    /**
     * Devuelve un objeto DefaultListModel de la Lista Clientes, método auxiliar para addVenta()
     * @return DefaultList de jList1 (lista clientes)
     */
    public DefaultListModel obtenerList(){
        DefaultListModel demo = new DefaultListModel();
        ListModel limo = jList1.getModel();
        for (int i = 0; i < limo.getSize(); i++){
            demo.addElement(limo.getElementAt(i));
        }
        return demo;
    }
    
    
    /**
     * Agrega el nombre del cliente a la lista cliente
     */
    public void addVenta(){
        DefaultListModel demo = obtenerList();
        demo.addElement(jnombreCliente.getText());
        jList1.setModel(demo);
    }
    
    /**
     * Devuelve el indice correspondiente al String localidad de la caja Localidad
     * @param localidad - String a devolver el indice de la caja localidad
     * @return el indice correspondiente en localidad
     */
    public int localMap(String localidad){
        ComboBoxModel cbm = jLocalidad.getModel();
        for (int i = 0; i < cbm.getSize(); i++){
            if (localidad.equals(cbm.getElementAt(i))){
                return i;
                }
        }
        return -1;
    }
       
    /**
     * Devuelve el ButtonModel del boton correspondiente al grupo que se introduzca como parametro
     * @param bg ButtonGroup al que corresponde
     * @param boton String actionCommand() del boton (idéntico al nombre)
     * @return El ButtonModel del botón correspondiente
     */
    public ButtonModel buttonMap(ButtonGroup bg, String boton){
        Enumeration<AbstractButton> proElements = bg.getElements();
        ArrayList<AbstractButton> buttonList = Collections.list(proElements);
            for (AbstractButton botonLista: buttonList){
                if (botonLista.getActionCommand().equals(boton)){
                    return botonLista.getModel();
                }
            }
        return null;
        }
    
    
    /**
     * Devuelve un ArrayList<Venta> con las ventas cuyo cliente sea "nombre"
     * @param nombre Nombre a filtrar de listaVentas
     * @return ArrayList<Venta> filtrada por "nombre"
     */
    public ArrayList<Venta> busquedaLista(String nombre){
        ArrayList<Venta> clie = new ArrayList<>();
        for (int i = 0; i < listaVentas.size(); i++){
            if (listaVentas.get(i).getNombreCliente().equals(nombre)){
                clie.add(listaVentas.get(i));
            }
        }
        return clie;
    }
    
    /**
     * Valida el nombre de jnombreCliente
     * @return true si el nombre es válido (Entre 16 y 1 letras) y false si no lo es
     */
    public boolean nombreCorrecto(){
        if (jnombreCliente.getText().isEmpty() || jnombreCliente.getText().length() >= 16){
            return false;
        } else {
            return true;
        }
    }
    
    /**
     * Muestra en la interfaz los valores correspondientes a la Venta "ven"
     * @param ven Venta a mostrar en la interfaz
     */
    public void escogerVenta(Venta ven){
        //Localidad
        jLocalidad.setSelectedItem((String) ven.getLocalidad());
        
        //Procesadores
        Enumeration<AbstractButton> enu1 = bgProcesadores.getElements();
        while (enu1.hasMoreElements()){
            AbstractButton ab1 = enu1.nextElement();
            if (ab1.getActionCommand().equals(ven.getProcesador())){
                bgProcesadores.setSelected(ab1.getModel(), true);
            }
        }
        
        //Memoria
        Enumeration<AbstractButton> enu2 = bgMemoria.getElements();
        while (enu2.hasMoreElements()){
            AbstractButton ab2 = enu2.nextElement();
            if (ab2.getActionCommand().equals(ven.getMemoria())){
                bgMemoria.setSelected(ab2.getModel(), true);
            }
        }
        
        //Monitor
        Enumeration<AbstractButton> enu3 = bgMonitor.getElements();
        while (enu3.hasMoreElements()){
            AbstractButton ab3 = enu3.nextElement();
            if (ab3.getActionCommand().equals(ven.getMonitor())){
                bgMonitor.setSelected(ab3.getModel(), true);
            }
        }
        
        //Disco Duro
        Enumeration<AbstractButton> enu4 = bgDiscoDuro.getElements();
        while (enu4.hasMoreElements()){
            AbstractButton ab4 = enu4.nextElement();
            if (ab4.getActionCommand().equals(ven.getDiscoDuro())){
                bgDiscoDuro.setSelected(ab4.getModel(), true);
            }
        }
        
        //Opciones
        jOpc1.setSelected(ven.isGrabadoraDVD());
        jOpc2.setSelected(ven.isWifi());
        jOpc3.setSelected(ven.isSincronizadorTV());
        jOpc4.setSelected(ven.isBackUpRestore());
        
        booleanButtons(false);
        
    }
    
    /**
     * Establece en la interfaz los valores por defecto
     */
    public void setDefault(){
        //Localidad
        jLocalidad.setSelectedItem("Villalba");
        
        //Procesadores
        Enumeration<AbstractButton> enu1 = bgProcesadores.getElements();
        while (enu1.hasMoreElements()){
            AbstractButton ab1 = enu1.nextElement();
            if (ab1.getActionCommand().equals("P4 3.0 Gb")){
                bgProcesadores.setSelected(ab1.getModel(), true);
            }
        }
        
        //Memoria
        Enumeration<AbstractButton> enu2 = bgMemoria.getElements();
        while (enu2.hasMoreElements()){
            AbstractButton ab2 = enu2.nextElement();
            if (ab2.getActionCommand().equals("128Mb")){
                bgMemoria.setSelected(ab2.getModel(), true);
            }
        }
        
        //Monitor
        Enumeration<AbstractButton> enu3 = bgMonitor.getElements();
        while (enu3.hasMoreElements()){
            AbstractButton ab3 = enu3.nextElement();
            if (ab3.getActionCommand().equals("15\"")){
                bgMonitor.setSelected(ab3.getModel(), true);
            }
        }
        
        //Disco Duro
        Enumeration<AbstractButton> enu4 = bgDiscoDuro.getElements();
        while (enu4.hasMoreElements()){
            AbstractButton ab4 = enu4.nextElement();
            if (ab4.getActionCommand().equals("60 Gb")){
                bgDiscoDuro.setSelected(ab4.getModel(), true);
            }
        }
        
        //Opciones
        jOpc1.setSelected(true);
        jOpc2.setSelected(true);
        jOpc3.setSelected(false);
        jOpc4.setSelected(false);        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBSalir;
    private javax.swing.ButtonGroup bgDiscoDuro;
    private javax.swing.ButtonGroup bgMemoria;
    private javax.swing.ButtonGroup bgMonitor;
    private javax.swing.ButtonGroup bgProcesadores;
    private javax.swing.JButton jBAdd;
    private javax.swing.JButton jBBus;
    private javax.swing.JButton jBCan;
    private javax.swing.JButton jBEli;
    private javax.swing.JButton jBGVe;
    private javax.swing.JButton jBMVe;
    private javax.swing.JRadioButton jDis1;
    private javax.swing.JRadioButton jDis2;
    private javax.swing.JRadioButton jDis3;
    private javax.swing.JRadioButton jDis4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JComboBox<String> jLocalidad;
    private javax.swing.JRadioButton jMem1;
    private javax.swing.JRadioButton jMem2;
    private javax.swing.JRadioButton jMem3;
    private javax.swing.JRadioButton jMem4;
    private javax.swing.JRadioButton jMon1;
    private javax.swing.JRadioButton jMon2;
    private javax.swing.JRadioButton jMon3;
    private javax.swing.JRadioButton jMon4;
    private javax.swing.JCheckBox jOpc1;
    private javax.swing.JCheckBox jOpc2;
    private javax.swing.JCheckBox jOpc3;
    private javax.swing.JCheckBox jOpc4;
    private javax.swing.JOptionPane jOptBus1;
    private javax.swing.JOptionPane jOptEli1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jPro1;
    private javax.swing.JRadioButton jPro2;
    private javax.swing.JRadioButton jPro3;
    private javax.swing.JRadioButton jPro4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jnombreCliente;
    // End of variables declaration//GEN-END:variables
}
